### ISSUE TITLE
IOError: stream closed in another thread

### ISSUE THREAD

**Issue by spieker** [Vonage/vonage-ruby-sdk#137]
Recently, we've updated the Nexmo gem to 6.1.0. Since then we're experiencing a lot of the following two errors when sending SMS:

* IOError: stream closed in another thread
* EOFError: end of file reached

The messages are actually being sent, but the `send_message` call then raises the error. The stack traces for both errors are basically looking the same:

```
IOError: stream closed in another thread
  from net/protocol.rb:217:in `wait_readable'
  from net/protocol.rb:217:in `rbuf_fill'
  from net/protocol.rb:191:in `readuntil'
  from net/protocol.rb:201:in `readline'
  from net/http/response.rb:40:in `read_status_line'
  from net/http/response.rb:29:in `read_new'
  from net/http.rb:1509:in `block in transport_request'
  from net/http.rb:1506:in `catch'
  from net/http.rb:1506:in `transport_request'
  from net/http.rb:1479:in `request'
  ...
  from net/http.rb:1472:in `block in request'
  from net/http.rb:920:in `start'
  from net/http.rb:1470:in `request'
  ...
  from nexmo/namespace.rb:91:in `request'
  from nexmo/sms.rb:106:in `send'
  ...
  from app/workers/sms_worker.rb:xx:in `perform'
  from sidekiq/processor.rb:196:in `execute_job'
  from sidekiq/processor.rb:164:in `block (2 levels) in process'
  from sidekiq/middleware/chain.rb:138:in `block in invoke'
  ...
  from sidekiq/middleware/chain.rb:140:in `block in invoke'
  ...
  from sidekiq/middleware/chain.rb:140:in `block in invoke'
  from sidekiq/batch/middleware.rb:54:in `call'
  from sidekiq/middleware/chain.rb:140:in `block in invoke'
  from sidekiq/middleware/chain.rb:143:in `invoke'
  from sidekiq/processor.rb:163:in `block in process'
  from sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
  from sidekiq/job_retry.rb:111:in `local'
  from sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
  from sidekiq/rails.rb:43:in `block in call'
  from active_support/execution_wrapper.rb:87:in `wrap'
  from active_support/reloader.rb:73:in `block in wrap'
  from active_support/execution_wrapper.rb:87:in `wrap'
  from active_support/reloader.rb:72:in `wrap'
  from sidekiq/rails.rb:42:in `call'
  from sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
  from sidekiq/processor.rb:257:in `stats'
  from sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
  from sidekiq/job_logger.rb:13:in `call'
  from sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
  from sidekiq/job_retry.rb:78:in `global'
  from sidekiq/processor.rb:124:in `block in dispatch'
  from sidekiq/logger.rb:10:in `with'
  from sidekiq/job_logger.rb:33:in `prepare'
  from sidekiq/processor.rb:123:in `dispatch'
  from sidekiq/processor.rb:162:in `process'
  from sidekiq/processor.rb:78:in `process_one'
  from sidekiq/processor.rb:68:in `run'
  from sidekiq/util.rb:15:in `watchdog'
  from sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by timcraft** [comment]
No obvious what the issue is there, but I don't think it's related to the 6.1.0 changes.

What version of the gem were you using before?

Can you reproduce the error outside of background jobs?

How fast are you sending messages? Have you tried throttling?

**Comment by spieker** [comment]
We've upgraded to 6.1.0 from 6.0.1. After downgrading, the problem seemed to be gone, so I opened the issue. However, after running for a couple of hours, I see new issues coming in now. Since it seems to not be related to the new Gem version right now, I'm closing the issue.
