### ISSUE TITLE
Nexmo verify method request error

### ISSUE THREAD

**Issue by Mracobes9** [Vonage/vonage-ruby-sdk#138]
Hi. I got following errors when i try to use method nexmo.verify.request:
1) attempt to read body out of block
2) end of file reached
Gem version: 5.2.0
Ruby version: 2.5.1

**Comment by timcraft** [comment]
Can you share minimal example code that fails and/or a stacktrace?

Have you tried upgrading to version 5.9.0 or 6.0.0 of the gem?

**Comment by hummusonrails** [comment]
Hi @Mracobes9, Just following up from @timcraft's comment. Are you able to share some failing example code? Also, I would recommend as well trying to upgrade the gem to a more recent version, if possible, and trying again. Thanks.

**Comment by rihardsgrislis** [comment]
Hey,

I'm using Gem version 5.7.1 and Ruby 2.3.8 and apart from the error reported ("end of file reached") I'm also seeing various other error but they all seem connected.

<img width="1175" alt="Screenshot 2020-01-17 at 17 03 47" src="https://user-images.githubusercontent.com/23099574/72622315-a01ff200-394b-11ea-80a0-2aa515445fe4.png">

For example, stack trace for "bad file descriptor":

```
/home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/openssl/buffering.rb:322:in `syswrite': Bad file descriptor (Errno::EBADF)
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/openssl/buffering.rb:322:in `do_write'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/openssl/buffering.rb:340:in `write'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/protocol.rb:229:in `write0'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/protocol.rb:203:in `block in write'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/protocol.rb:220:in `writing'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/protocol.rb:202:in `write'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http/generic_request.rb:334:in `write_header'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http/generic_request.rb:186:in `send_request_with_body'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http/generic_request.rb:121:in `exec'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http.rb:1421:in `block in transport_request'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http.rb:1420:in `catch'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http.rb:1420:in `transport_request'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http.rb:1393:in `request'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http.rb:1386:in `block in request'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http.rb:853:in `start'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http.rb:1384:in `request'
    from gems/nexmo-5.7.1/lib/nexmo/namespace.rb:75:in `request'
    from gems/nexmo-5.7.1/lib/nexmo/sms.rb:10:in `send'
```

The code we're using is straightforward:

```
NEXMO.sms.send(
    to: '+371XXXXXXXX, # example
    from: "Name",
    text: "Hello, testing."
)
```

It doesn't always fail. When I called it from rails console few times it worked but in Sidekiq it appears to be failing. I don't know yet if all of the requests fail or only some part of them. I will get back about that.

**Comment by rihardsgrislis** [comment]
I checked compared your 5.9.0 with 5.7.1 and it doesn't appear that something has changed that would be connected to this so I'm not upgrading now. 
What TLS versions do you support? Maybe 2.3.8 Ruby's OpenSSL doesn't work with your TLS version?

**Comment by Mracobes9** [comment]
My backtrace for bad file descriptor
```

/usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:181→ wait_readable
--
/usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:181→ rbuf_fill
/usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:157→ readuntil
/usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:167→ readline
/usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb:40→ read_status_line
/usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http/response.rb:29→ read_new
/usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1494→ block in transport_request
/usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1491→ catch
/usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1491→ transport_request
/usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1464→ request
/usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1457→ block in request

/usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:910→ start
/usr/share/rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:1455→ request
nexmo-5.2.0/lib/nexmo/namespace.rb:59→ request
nexmo-5.2.0/lib/nexmo/verify.rb:8→ request
app/models/user.rb:177→ nexmo_verification
app/models/user.rb:140→ simple_send_code
app/models/user.rb:98→ resend_code
app/controllers/users/registrations_controller.rb:92→ create
actionpack-5.1.6/lib/action_controller/metal/basic_implicit_render.rb:4→ send_action
actionpack-5.1.6/lib/abstract_controller/base.rb:186→ process_action
actionpack-5.1.6/lib/action_controller/metal/rendering.rb:30→ process_action
actionpack-5.1.6/lib/abstract_controller/callbacks.rb:20→ block in process_action
activesupport-5.1.6/lib/active_support/callbacks.rb:131→ run_callbacks
actionpack-5.1.6/lib/abstract_controller/callbacks.rb:19→ process_action
actionpack-5.1.6/lib/action_controller/metal/rescue.rb:20→ process_action
actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:32→ block in process_action
activesupport-5.1.6/lib/active_support/notifications.rb:166→ block in instrument
activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21→ instrument
activesupport-5.1.6/lib/active_support/notifications.rb:166→ instrument
actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:30→ process_action
actionpack-5.1.6/lib/action_controller/metal/params_wrapper.rb:252→ process_action
activerecord-5.1.6/lib/active_record/railties/controller_runtime.rb:22→ process_action
actionpack-5.1.6/lib/abstract_controller/base.rb:124→ process
actionpack-5.1.6/lib/action_controller/metal.rb:189→ dispatch
actionpack-5.1.6/lib/action_controller/metal.rb:253→ dispatch
actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:49→ dispatch
actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:31→ serve
actionpack-5.1.6/lib/action_dispatch/routing/mapper.rb:16→ block in <class:Constraints>
actionpack-5.1.6/lib/action_dispatch/routing/mapper.rb:46→ serve
actionpack-5.1.6/lib/action_dispatch/journey/router.rb:50→ block in serve
actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33→ each
actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33→ serve
actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:844→ call
rack-2.0.5/lib/rack/session/abstract/id.rb:232→ context
rack-2.0.5/lib/rack/session/abstract/id.rb:226→ call
actionpack-5.1.6/lib/action_dispatch/middleware/cookies.rb:613→ call
warden-1.2.7/lib/warden/manager.rb:36→ block in call
warden-1.2.7/lib/warden/manager.rb:35→ catch

warden-1.2.7/lib/warden/manager.rb:35→ call
rack-2.0.5/lib/rack/etag.rb:25→ call
rack-2.0.5/lib/rack/conditional_get.rb:38→ call
rack-2.0.5/lib/rack/head.rb:12→ call
lib/middleware/catch_json_parse_errors.rb:8→ call
actionpack-5.1.6/lib/action_dispatch/middleware/callbacks.rb:26→ block in call
activesupport-5.1.6/lib/active_support/callbacks.rb:97→ run_callbacks
actionpack-5.1.6/lib/action_dispatch/middleware/callbacks.rb:24→ call
airbrake-5.8.1/lib/airbrake/rack/middleware.rb:52→ call
actionpack-5.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:59→ call
actionpack-5.1.6/lib/action_dispatch/middleware/show_exceptions.rb:31→ call
railties-5.1.6/lib/rails/rack/logger.rb:36→ call_app
railties-5.1.6/lib/rails/rack/logger.rb:24→ block in call
activesupport-5.1.6/lib/active_support/tagged_logging.rb:69→ block in tagged
activesupport-5.1.6/lib/active_support/tagged_logging.rb:26→ tagged
activesupport-5.1.6/lib/active_support/tagged_logging.rb:69→ tagged
railties-5.1.6/lib/rails/rack/logger.rb:24→ call
actionpack-5.1.6/lib/action_dispatch/middleware/remote_ip.rb:79→ call
request_store-1.4.1/lib/request_store/middleware.rb:19→ call
actionpack-5.1.6/lib/action_dispatch/middleware/request_id.rb:25→ call
rack-2.0.5/lib/rack/runtime.rb:22→ call
activesupport-5.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:27→ call
actionpack-5.1.6/lib/action_dispatch/middleware/executor.rb:12→ call
rack-2.0.5/lib/rack/sendfile.rb:111→ call
rack-cors-1.0.2/lib/rack/cors.rb:97→ call
railties-5.1.6/lib/rails/engine.rb:522→ call
puma-3.11.4/lib/puma/configuration.rb:225→ call

puma-3.11.4/lib/puma/server.rb:632→ handle_request
puma-3.11.4/lib/puma/server.rb:446→ process_client
puma-3.11.4/lib/puma/server.rb:306→ block in run
puma-3.11.4/lib/puma/thread_pool.rb:120→ block in spawn_thread


```

**Comment by Mracobes9** [comment]
My code:
```
    methods = {
        sms: 6,
        voice: 7
    }

    @nexmo ||= Nexmo::Client.new(
        api_key: ENV['NEXMO_KEY'],
        api_secret: ENV['NEXMO_SECRET']
    )
    @nexmo.verify.request(
        number: send_phone,
        brand: 'test',
        sender_id: 'test',
        workflow_id: methods[method.to_sym],
        code_length: '4',
        pin_expiry: expiry,
        next_event_wait: expiry,
        lg: 'ru-ru'
    )
```

**Comment by rihardsgrislis** [comment]
Another error I'm seeing (also looks related):

```
/home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/protocol.rb:230:in `write0': undefined method `+' for nil:NilClass (NoMethodError)
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/protocol.rb:203:in `block in write'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/protocol.rb:220:in `writing'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/protocol.rb:202:in `write'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http/generic_request.rb:334:in `write_header'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http/generic_request.rb:186:in `send_request_with_body'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http/generic_request.rb:121:in `exec'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http.rb:1421:in `block in transport_request'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http.rb:1420:in `catch'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http.rb:1420:in `transport_request'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http.rb:1393:in `request'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http.rb:1386:in `block in request'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http.rb:853:in `start'
    from /home/creative/.rbenv/versions/2.3.8/lib/ruby/2.3.0/net/http.rb:1384:in `request'
    from gems/nexmo-5.7.1/lib/nexmo/namespace.rb:75:in `request'
    from gems/nexmo-5.7.1/lib/nexmo/sms.rb:10:in `send'
```

**Comment by timcraft** [comment]
@Mracobes9 I suspect your issue is related to threading.

Generally speaking burying HTTP calls within an ActiveRecord model isn't good practice, so I would recommend moving that code to the controller. Specifically I think your memoization of the `@nexmo` instance variable is the source of the problem. Either create a new `Nexmo::Client` object every time the method is called (the simpler solution), or use something like a connection pool if you want to re-use `Nexmo::Client` objects across threads.

**Comment by timcraft** [comment]
@rihardssceredins Ruby 2.3 is EOL and unmaintained, so I'd recommend upgrading to Ruby 2.5 or newer if you can. There have been a number of changes to net/protocol.rb since Ruby 2.3 which might fix your issue. I'd also recommend checking your code to make sure you aren't re-using `Nexmo::Client` objects across threads. Same advice as above: either create new client objects each time, or use some threadsafe wrapper like a connection pool.

**Comment by rihardsgrislis** [comment]
@timcraft yes, I'm aware. Sadly I can't upgrade to Ruby 2.5 any time soon and from what I understand 5.7.1 supports Ruby 2.3 so my expectation is that it should work. :/

**Comment by timcraft** [comment]
@rihardssceredins Can you share the code you're using to set that `NEXMO` constant?

If you're re-using a `Nexmo::Client` object across threads / sidekiq jobs then that'll likely be what's causing those exceptions. Client objects aren't meant to be shared across threads.

**Comment by rihardsgrislis** [comment]
@timcraft you might right about that.

It appears that Nexmo::Client is used in initializer and assigned to `NEXMO`:

```
NEXMO = Nexmo::Client.new(
  api_key: NEXMO_API_KEY,
  api_secret: NEXMO_API_SECRET_KEY
)
```

Will try to refactor this to directly initialize the client.

**Comment by rihardsgrislis** [comment]
@timcraft it appears that it was the culprit of all my issues. Errors are gone and haven't occured since new release. Thank you so much! Would be nice if documentation had something to say on this. :)

**Comment by timcraft** [comment]
@rihardssceredins Yep. I have no idea why you would want to assign a constant in an initializer.

Docs can always be improved but this issue isn't specific to nexmo-ruby, it's not even specific to net/http—you'll get the same problems if you try to use `Redis.new` in the same way.

The majority of regular use cases can be handled with simple code like this:

```ruby
client = Nexmo::Client.new
client.sms.send(...)
```

Put that code in a controller, and you can extract it directly into a background job if/when you need to. If you don't like the aesthetics of the credentials in your code there are two solutions for that: use environment variables, or use `Nexmo.configure` (added in v6).

That's the code the examples in the documentation use. If you want to use memoization or some other technique to eliminate the instance variable from your code then you need to make sure you don't share that reference between threads (or protect those calls appropriately).
